### ISSUE TITLE
Increase history limit

### ISSUE THREAD

**Issue by fhoshino** [k-t-corp/mastodon-issues#13]
Current maximum history limit for 3 hours ago post

**Comment by KTachibanaM** [comment]
Home feed count has been increased from 400 to 4000 as in https://github.com/k-t-corp/mastodon-issues/blob/master/higher-feed-count.diff#L10

**Comment by KTachibanaM** [comment]
https://github.com/tootsuite/mastodon/issues/2301

**Comment by KTachibanaM** [comment]
This seems that it's going to work..? https://github.com/tootsuite/mastodon/pull/4016

**Comment by KTachibanaM** [comment]
I was able to scroll beyond 3 hours in the **federated timeline** in this version. Closing for now unless it's still an issue.
