### ISSUE TITLE
Pixiv preview issue

### ISSUE THREAD

**Issue by Frederick888** [k-t-corp/mastodon-issues#18]
Mastodon per se is capable of pulling Pixiv preview images according to tootsuite/mastodon#13213, so perhaps you could try cURL'ing the links mentioned in that ticket in your VPS to see whether there is actually any server-side filtering going on. If this is the case I'd be happy to provide a reverse proxy or the like.

But right now there seems to be another issue. IIRC it used to simply show nothing for Pixiv links however they now have got empty previews with `background-image: url("null");`. I'd appreciate it if you could look into it :)
![image](https://user-images.githubusercontent.com/4507647/80219448-cc06ee00-8685-11ea-8525-1f2758ddf806.png)

**Comment by KTachibanaM** [comment]
Looks like the instance IP has been banned by Pixiv server(s). When attempting to generate a preview card for a toot with a Pixiv link, the instance will fail to download the preview image from Pixiv server(s), hence the instance is not able to show Pixiv previews.
