### ISSUE TITLE
Pixiv preview has stopped working

### ISSUE THREAD

**Issue by Frederick888** [k-t-corp/mastodon-issues#46]
Check out posts from https://pawoo.net/@ogatarin

**Comment by KTachibanaM** [comment]
(For my own record) It started to miss `embed_urls` from April 22.

**Comment by KTachibanaM** [comment]
Looks like mastodon switches from crawling from opengraph to oembed, and it is able to successfully download the preview image now, hence the [embed_url](https://github.com/k-t-corp/mastodon-issues/blob/dccec573b8dafd72f4fa96a77f42084d032ef353/code-patches/pixiv-preview-with-embed-url.diff) hack is no longer needed.
