### ISSUE TITLE
Migrate to AWS

### ISSUE THREAD

**Issue by Frederick888** [k-t-corp/mastodon-issues#6]
Especially the database services for higher stability and lower maintenance overheads.

Related: #3

**Comment by KTachibanaM** [comment]
FYI https://github.com/aus-social/mastodon-aws

**Comment by KTachibanaM** [comment]
能搞个Terraform的233

**Comment by Frederick888** [comment]
没用过Terraform查了一下感觉可以的。AWS开EKS还有个每月的control panel费用IIRC，GCP的话大陆访问又是问题。

**Comment by Frederick888** [comment]
https://github.com/aus-social/mastodon-aws 这个没算ES的价格啊，AWS的ES还是不便宜的……

**Comment by Frederick888** [comment]
https://cloud.elastic.co/pricing ES自家的比AWS便宜

**Comment by KTachibanaM** [comment]
所以不算价格的话AWS全家桶大概可以是
web - ec2
pgsql - rds
redis - elasticache
es - elasticsearch service
log - cloudwatch

**Comment by Frederick888** [comment]
| Service | Size | $/h | $/mo | Link |
| -- | -- | -- | -- | -- |
| EC2 | t3.small | 0.0208 | 15.6 | https://aws.amazon.com/ec2/pricing/on-demand/ |
| PostgreSQL | db.t3.small | 0.036 | 27.0 | https://aws.amazon.com/rds/postgresql/pricing/ |
| ElasticCache | cache.t3.micro | 0.017 | 12.75 | https://aws.amazon.com/elasticache/pricing/ |
| ElasticSearch | t2.small.elasticsearch | 0.036 | 27.0 | https://aws.amazon.com/elasticsearch-service/pricing/ |
| CloudWatch | Collect + Store 2GB | (0.50+0.03)/GB | 1.06 | https://aws.amazon.com/cloudwatch/pricing/ |
| Lambda | Request + Duration | 100K + 0.5sec&128MB=$0.0000002083/log | 0.12415 | https://aws.amazon.com/lambda/pricing/ |
| | | | |
| Total | | | 83.53415 |

Note that small ElasticSearch instances have got a 35GB EBS limit: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#ebsresource. And based on my experience it's better to provision a t2.medium.elasticsearch x 2 (2 availability zones) cluster at least for production lol.

Additional fees may still incur for S3 service.

**Comment by KTachibanaM** [comment]
Please also add Promethes and Grafana for metrics, dashboard and monitoring. Datadog costs a million.

**Comment by Frederick888** [comment]
AWS has got its built-in dashboards for various services which should be sufficient for a Mastodon stack, unless you want any additional features such as public dashboards and so on.

There is something called [Grafana Cloud](https://grafana.com/products/cloud/) which starts at $49/mo but for one thing imho it's an overkill, for another I'm almost sure that you cannot, at least easily, collect metrics from AWS SaaS products.

**Comment by KTachibanaM** [comment]
Started two starter issues #10 and #11
