### ISSUE TITLE
Higher API throttle

### ISSUE THREAD

**Issue by fhoshino** [k-t-corp/mastodon-issues#7]
Expend the limits for this instance for:

1. History: not sure about this instance, but pawoo only allow up to 4 hours of history and certain amount of posts, then lookup will hit a 429 too many request limiter. 

![brave_2020-03-06_21-14-59](https://user-images.githubusercontent.com/771955/76086713-9b90c500-5fef-11ea-8610-6c16b77dbcdf.png)

**Comment by KTachibanaM** [comment]
@fhoshino Is there a configuration to set those limits?

**Comment by KTachibanaM** [comment]
https://docs.joinmastodon.org/api/rate-limits/

https://github.com/tootsuite/mastodon/blob/master/config/initializers/rack_attack.rb

**Comment by KTachibanaM** [comment]
word count and picture per post count has been moved to #9

**Comment by KTachibanaM** [comment]
Higher API throttle is something that people tried here https://github.com/tootsuite/mastodon/pull/11646

**Comment by KTachibanaM** [comment]
`throttle_authenticated_api` has been increased from 300 per 5 minute to 1500 per 5 minute

https://github.com/k-t-corp/mastodon-issues/blob/master/higher-throttle.diff#L10
